name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
  download: #added
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download file and place in path
        uses: actions/download-artifact@v4
        with:
          name: hello-artifac
          path: ./artifacts
      - name: Display Content
        run: cat ./artifacts/hello.txt
        
